version: '3.8'

services:
  storyscape:
    image: "localhost/storyscape:latest"
    networks:
      - public
    deploy:
      restart_policy:
        condition: any
      mode: global
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storyscape.rule=PathPrefix(`/storyscape/`)"
      - "traefik.http.routers.storyscape.middlewares=storyscape-strip"
      - "traefik.http.middlewares.storyscape-strip.stripprefix.prefixes=/storyscape"
      - "traefik.http.routers.storyscape.entrypoints=web"
      - "traefik.http.services.storyscape.loadbalancer.server.port=80"
      - "traefik.http.routers.storyscape.service=storyscape"

networks:
  public:
    external: true
